services:
  mongo:
    image: mongo:4
    restart: unless-stopped
    container_name: ${DB_HOST}
    ports:
      - ${DB_PORT}:27017
    volumes:
      - mongo_rc_setup:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    networks:
      - rc_setup
      
  backend:
    build: .
    container_name: ${APP_HOST}
    restart: unless-stopped
    ports:
      - ${APP_PORT}:3000
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    networks:
      - rc_setup
      - nginx-proxy
    enviroment:
      VIRTUAL_HOST: api.rc_setup.ivancm.info
      LETSENCRYPT_HOST: api.rc_setup.ivancm.info
      LETSENCRYPT_EMAIL: admin@rc_setup.ivancm.info

volumes:
  node_modules:
  mongo_rc_setup:
networks:
  rc_setup:
  nginx-proxy:
    external: true